In [2]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [5]:
# ── Configuración ──────────────────────────────────────────
DATASET_KAGGLE = "azminetoushikwasi/-lionel-messi-all-club-goals"  # ← CAMBIAR: usuario/nombre-dataset
# ───────────────────────────────────────────────────────────

# Descarga a caché local (no re-descarga si ya está actualizado)
path = kagglehub.dataset_download(DATASET_KAGGLE)

# Detecta el archivo automáticamente
archivos = os.listdir(path)
print("Archivos descargados:", archivos)

# Carga el primer archivo CSV encontrado
df_raw = pd.read_csv(f"{path}/{archivos[0]}")
print(f"✅ Dataset cargado — Filas: {df.shape[0]} | Columnas: {df.shape[1]}")

Archivos descargados: ['data.csv']
✅ Dataset cargado — Filas: 704 | Columnas: 13

In [6]:

# ─── Primeras y últimas filas ──────────────────────────────────────────────
print('\n--- Primeras 5 filas ---')
display(df_raw.head())

print('\n--- Últimas 5 filas ---')
display(df_raw.tail())

# ─── Dimensiones ───────────────────────────────────────────────────────────
print(f'Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}')

# ─── Tipos de datos ────────────────────────────────────────────────────────
print('\n--- Info general ---')
df_raw.info()

# ─── Valores nulos por columna ─────────────────────────────────────────────
print('\n--- Nulos por columna ---')
# Verificamos si hay algún nulo en toda la tabla
if df_raw.isnull().sum().sum() == 0:
    print('✅ Sin valores nulos')
else:
    # Sino mostramos tabla filtrada de nulos
    nulos = pd.DataFrame({
        'Nulos': df_raw.isnull().sum(),
        'Porcentaje': (df_raw.isnull().sum() / len(df_raw) * 100).round(2)
    })
    display(nulos[nulos['Nulos'] > 0])

# ─── Duplicados ────────────────────────────────────────────────────────────
print(f'\nFilas duplicadas: {df.duplicated().sum()}')

# ─── Estadísticas descriptivas ─────────────────────────────────────────────
print('\n--- Estadísticas descriptivas ---')
display(df.describe())

--- Primeras 5 filas ---

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,2:00,Left-footed shot,Ronaldinho Gaacho
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,3:00,Left-footed shot,NaN
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,2:00,Left-footed shot,Samuel Etoo
3,05/06,LaLiga,19,1/15/06,H,FC Barcelona,Athletic Bilbao,2:01,RW,50,2:01,Left-footed shot,Mark van Bommel
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,2:00,Left-footed shot,Ronaldinho Gaacho

--- Últimas 5 filas ---

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
699,22/23,Ligue 1,21,2/1/23,A,Paris Saint-Germain,Montpellier HSC,1:3,SS,72,0:2,Left-footed shot,Fabián Ruiz
700,22/23,Ligue 1,22,2/4/23,H,Paris Saint-Germain,FC Toulouse,2:1,SS,58,2:1,Left-footed shot,Achraf Hakimi
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,4:3,Direct free kick,\t
702,22/23,Ligue 1,25,2/26/23,A,Paris Saint-Germain,Olympique Marseille,0:3,CF,29,0:2,Right-footed shot,Kylian Mbappé
703,22/23,Ligue 1,26,3/4/23,H,Paris Saint-Germain,FC Nantes,4:2,CF,12,1:0,Left-footed shot,NaN

Filas: 704 | Columnas: 13

--- Info general ---
<class 'pandas.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            704 non-null    str
 1   Competition       704 non-null    str
 2   Matchday          704 non-null    str
 3   Date              704 non-null    str
 4   Venue             704 non-null    str
 5   Club              704 non-null    str
 6   Opponent          704 non-null    str
 7   Result            704 non-null    str
 8   Playing_Position  704 non-null    str
 9   Minute            704 non-null    str
 10  At_score          704 non-null    str
 11  Type              703 non-null    str
 12  Goal_assist       490 non-null    str
dtypes: str(13)
memory usage: 71.6 KB

--- Nulos por columna ---

             Nulos  Porcentaje
Type             1        0.14
Goal_assist    214       30.40

Filas duplicadas: 0

--- Estadísticas descriptivas ---

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
count,704,704,704,704,704,704,704,704,704,704,704,703,490
unique,19,10,48,455,2,2,98,55,9,97,46,12,71
top,11-Dec,LaLiga,Group Stage,03/07/12,H,FC Barcelona,Sevilla FC,4:00,CF,55,1:00,Left-footed shot,Luis Suarez
freq,73,474,80,5,420,672,38,47,276,14,98,436,48

In [7]:
# Cantidad total
print(f'Duplicados: {df_raw.duplicated().sum()}')

# Ver las filas duplicadas
display(df_raw[df_raw.duplicated(keep=False)])  # muestra todas las copias

Duplicados: 0

Empty DataFrame
Columns: [Season, Competition, Matchday, Date, Venue, Club, Opponent, Result, Playing_Position, Minute, At_score, Type, Goal_assist]
Index: []